version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d order_service" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order_service:
    container_name: order_service
    restart: unless-stopped
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - order-network

volumes:
  postgres_data:

networks:
  order-network: